export const characters = [
  {
    "name": "Jiren máxima potencia",
    "start_card": false,
    "univers": 11,
    "picture": "jiren_maxima.png",
    "power": 6,
    "hability": 4,
    "health": 42,
    "Y_damage": 5,
    "G_damage": 5,
    "P_damage": 5,
    "R_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento de puños de energia",
    "fight_combo": "YPGRB",
    "fight_combo_damage": 38,
    "ball_combo_name": "Magnetrón sobrecalentado",
    "ball_combo": "YYPPRR",
    "ball_combo_damage": 60,
    "transf_min_value": 4,
    "protection_divider": 3,
    "transf_damage": 5,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 1,
    "transf_cards": ""
  },
  {
    "name": "Jiren",
    "start_card": true,
    "univers": 11,
    "picture": "jiren.png",
    "power": 5,
    "hability": 3,
    "health": 42,
    "Y_damage": 4,
    "G_damage": 5,
    "P_damage": 4,
    "R_damage": 5,
    "protection_combo": "BBBB",
    "fight_combo_name": "Ola de potencia invisible",
    "fight_combo": "PPPRR",
    "fight_combo_damage": 32,
    "ball_combo_name": "Impacto de potencia",
    "ball_combo": "YYPRR",
    "ball_combo_damage": 45,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [0]
  },
  {
    "name": "Anilaza",
    "start_card": false,
    "univers": 3,
    "picture": "anilaza.png",
    "power": 5,
    "hability": 4,
    "health": 37,
    "Y_damage": 4,
    "G_damage": 3,
    "P_damage": 4,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Puño interdimensional",
    "fight_combo": "GPRB",
    "fight_combo_damage": 25,
    "ball_combo_name": "Bola de energia máxima potencia",
    "ball_combo": "YYPPR",
    "ball_combo_damage": 35,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "Paparoni, Koichiarator",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Son Goku Ultra Instinto",
    "start_card": false,
    "univers": 7,
    "picture": "goku_ultra_instinto.png",
    "power": 6,
    "hability": 4,
    "health": 34,
    "Y_damage": 5,
    "G_damage": 5,
    "P_damage": 5,
    "R_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento ultra instinct",
    "fight_combo": "YPGRB",
    "fight_combo_damage": 40,
    "ball_combo_name": "Kamehameha ultra instinct",
    "ball_combo": "PPYRRR",
    "ball_combo_damage": 60,
    "transf_min_value": 11,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Ultra Instinto (presagio)",
    "start_card": false,
    "univers": 7,
    "picture": "son_goku_ultra_instinto.png",
    "power": 6,
    "hability": 4,
    "health": 34,
    "Y_damage": 4,
    "G_damage": 5,
    "P_damage": 4,
    "R_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGRR",
    "fight_combo_damage": 35,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPYRRR",
    "ball_combo_damage": 41,
    "transf_min_value": 10,
    "protection_divider": 3,
    "transf_damage": 4,
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Super Saiyan Blue + Kaioken x10",
    "start_card": false,
    "univers": 7,
    "picture": "son_goku_ss_blue_kaioken.png",
    "power": 6,
    "hability": 3,
    "health": 34,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 4,
    "R_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Aura de Kaio x10",
    "fight_combo": "PPGRR",
    "fight_combo_damage": 30,
    "ball_combo_name": "Aura de Kaio x20",
    "ball_combo": "PPYRRR",
    "ball_combo_damage": 36,
    "transf_min_value": 8,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Super Saiyan Blue",
    "start_card": false,
    "univers": 7,
    "picture": "goku_blue.png",
    "power": 5,
    "hability": 3,
    "health": 34,
    "Y_damage": 3,
    "G_damage": 3,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo_name": "Teletransportación + ataque",
    "fight_combo": "BPPG",
    "fight_combo_damage": 26,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPYRR",
    "ball_combo_damage": 29,
    "transf_min_value": 7,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Super Saiyan Dios",
    "start_card": false,
    "univers": 7,
    "picture": "son_goku_ss_dios.png",
    "power": 5,
    "hability": 3,
    "health": 34,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo_name": "Teletransportación + ataque",
    "fight_combo": "BPGR",
    "fight_combo_damage": 25,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPYRR",
    "ball_combo_damage": 27,
    "transf_min_value": 6,
    "protection_divider": 2,
    "transf_damage": 2,
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Super Saiyan 3",
    "start_card": false,
    "univers": 7,
    "picture": "son_goku_ss3.png",
    "power": 5,
    "hability": 3,
    "health": 34,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGGR",
    "fight_combo_damage": 23,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPYRR",
    "ball_combo_damage": 24,
    "transf_min_value": 5,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,"PPGGR",0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Super Saiyan 2",
    "start_card": false,
    "univers": 7,
    "picture": "son_goku_ss.png",
    "power": 5,
    "hability": 2,
    "health": 34,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "BPPG",
    "fight_combo_damage": 20,
    "ball_combo_name": "Kamehameha teletransportado",
    "ball_combo": "PPYRB",
    "ball_combo_damage": 22,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku Super Saiyan",
    "start_card": false,
    "univers": 7,
    "picture": "goku_ss1.png",
    "power": 4,
    "hability": 2,
    "health": 34,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Teletransportación + ataque",
    "fight_combo": "BPG",
    "fight_combo_damage": 18,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPYY",
    "ball_combo_damage": 20,
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 11,
    "transf_cards": ""
  },
  {
    "name": "Son Goku",
    "start_card": true,
    "univers": 7,
    "picture": "goku.png",
    "power": 3,
    "hability": 2,
    "health": 34,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Kamehameha",
    "fight_combo": "PPY",
    "fight_combo_damage": 17,
    "ball_combo_name": "Genkidama",
    "ball_combo": "PPYRR",
    "ball_combo_damage": 35,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [10,9,8,7,6,5,4,3]
  },
  {
    "name": "Vegeta Super Saiyan Blue Evolution",
    "start_card": false,
    "univers": 7,
    "picture": "vegeta_ss_blue_evolution.png",
    "power": 6,
    "hability": 4,
    "health": 33,
    "Y_damage": 4,
    "G_damage": 5,
    "P_damage": 4,
    "R_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Destello final máxima potencia",
    "fight_combo": "YPPRRR",
    "fight_combo_damage": 41,
    "ball_combo_name": "Implosión",
    "ball_combo": "YPGRRR",
    "ball_combo_damage": 55,
    "transf_min_value": 9,
    "protection_divider": 3,
    "transf_damage": 4,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": 16,
    "transf_cards": ""
  },
  {
    "name": "Vegeta Super Saiyan Blue",
    "start_card": false,
    "univers": 7,
    "picture": "vegeta_ss_blue.png",
    "power": 5,
    "hability": 3,
    "health": 33,
    "Y_damage": 3,
    "G_damage": 3,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGR",
    "fight_combo_damage": 29,
    "ball_combo_name": "Destello final definitivo",
    "ball_combo": "YPPRR",
    "ball_combo_damage": 33,
    "transf_min_value": 7,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": 16,
    "transf_cards": ""
  },
  {
    "name": "Vegeta Super Saiyan 2",
    "start_card": false,
    "univers": 7,
    "picture": "vegeta_ss2.png",
    "power": 5,
    "hability": 3,
    "health": 33,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Ataque Big Bang",
    "fight_combo": "YYPR",
    "fight_combo_damage": 24,
    "ball_combo_name": "Destello final",
    "ball_combo": "YPPRR",
    "ball_combo_damage": 27,
    "transf_min_value": 5,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,"PPGGR",0,0,0,0,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": 16,
    "transf_cards": ""
  },
  {
    "name": "Vegeta Super Saiyan",
    "start_card": false,
    "univers": 7,
    "picture": "vegeta_ss.png",
    "power": 4,
    "hability": 2,
    "health": 33,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 20,
    "ball_combo_name": "Cañón Galick",
    "ball_combo": "YYPP",
    "ball_combo_damage": 23,
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,1,1],
    "fusion_needed": "",
    "transf_origin_card": 16,
    "transf_cards": ""
  },
  {
    "name": "Vegeta",
    "start_card": true,
    "univers": 7,
    "picture": "vegeta.png",
    "power": 3,
    "hability": 2,
    "health": 33,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 19,
    "ball_combo_name": "Cañón Galick",
    "ball_combo": "YPP",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [15,14,13,12]
  },
  {
    "name": "Toppo dios de la destrucción",
    "start_card": false,
    "univers": 11,
    "picture": "toppo_dios.png",
    "power": 6,
    "hability": 2,
    "health": 32,
    "Y_damage": 5,
    "G_damage": 4,
    "P_damage": 4,
    "R_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGGR",
    "fight_combo_damage": 35,
    "ball_combo_name": "Bola de destrucciión",
    "ball_combo": "YYPGRR",
    "ball_combo_damage": 45,
    "transf_min_value": 4,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 18,
    "transf_cards": ""
  },
  {
    "name": "Toppo",
    "start_card": true,
    "univers": 11,
    "picture": "toppo.png",
    "power": 5,
    "hability": 4,
    "health": 32,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 5,
    "protection_combo": "BBBB",
    "fight_combo_name": "Justice Flash",
    "fight_combo": "YYPR",
    "fight_combo_damage": 26,
    "ball_combo_name": "Justice Crush",
    "ball_combo": "PPRRR",
    "ball_combo_damage": 31,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [17]
  },
  {
    "name": "Kefla Super Saiyan",
    "start_card": false,
    "univers": 6,
    "picture": "kefla_ss.png",
    "power": 6,
    "hability": 3,
    "health": 32,
    "Y_damage": 3,
    "G_damage": 5,
    "P_damage": 4,
    "R_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Ráfaga gigante",
    "fight_combo": "PPYRR",
    "fight_combo_damage": 35,
    "ball_combo_name": "Oleada gigante",
    "ball_combo": "YYRRRR",
    "ball_combo_damage": 40,
    "transf_min_value": 3,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "Caulifa, Kale",
    "transf_origin_card": 20,
    "transf_cards": ""
  },
  {
    "name": "Kefla",
    "start_card": false,
    "univers": 6,
    "picture": "kefla.png",
    "power": 5,
    "hability": 4,
    "health": 32,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGGR",
    "fight_combo_damage": 29,
    "ball_combo_name": "Cañón de energía",
    "ball_combo": "YYRRR",
    "ball_combo_damage": 33,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "Caulifa, Kale",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Kale Super Saiyan 2",
    "start_card": false,
    "univers": 6,
    "picture": "kale_ss1_dreta.png",
    "power": 6,
    "hability": 3,
    "health": 30,
    "Y_damage": 4,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGGR",
    "fight_combo_damage": 30,
    "ball_combo_name": "Oleada de energía",
    "ball_combo": "YYPRRR",
    "ball_combo_damage": 32,
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 23,
    "transf_cards": ""
  },
  {
    "name": "Kale Super Saiyan 2 (fuera de control)",
    "start_card": false,
    "univers": 6,
    "picture": "kale_ss1.png",
    "power": 5,
    "hability": 3,
    "health": 30,
    "Y_damage": 4,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 5,
    "protection_combo": "BBBB",
    "fight_combo_name": "Explosión de energía",
    "fight_combo": "PGRR",
    "fight_combo_damage": 28,
    "ball_combo_name": "Ráfaga de meteoritos",
    "ball_combo": "YYRRR",
    "ball_combo_damage": 36,
    "transf_min_value": 5,
    "protection_divider": 3,
    "transf_damage": 4,
    "extra_habilities": [0,0,0,"PPRRR",0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 23,
    "transf_cards": ""
  },
  {
    "name": "Kale",
    "start_card": true,
    "univers": 6,
    "picture": "kale.png",
    "power": 3,
    "hability": 4,
    "health": 30,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [22,21]
  },
  {
    "name": "Hit",
    "start_card": true,
    "univers": 6,
    "picture": "hit.png",
    "power": 6,
    "hability": 2,
    "health": 30,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Salto temporal + ataque",
    "fight_combo": "PGRBB",
    "fight_combo_damage": 32,
    "ball_combo_name": "Bloqueo temporal + bola de energia",
    "ball_combo": "YPRRBB",
    "ball_combo_damage": 40,
    "transf_min_value": "",
    "protection_divider": 3,
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Son Gohan Estado Definitivo",
    "start_card": false,
    "univers": 7,
    "picture": "son_gohan_definitivo.png",
    "power": 5,
    "hability": 3,
    "health": 28,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Masenko",
    "fight_combo": "YPPRR",
    "fight_combo_damage": 27,
    "ball_combo_name": "Kamehameha definitivo",
    "ball_combo": "PPYRR",
    "ball_combo_damage": 31,
    "transf_min_value": 5,
    "protection_divider": 3,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,0,0,0,1,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 28,
    "transf_cards": ""
  },
  {
    "name": "Son Gohan Super Saiyan 2",
    "start_card": false,
    "univers": 7,
    "picture": "son_gohan_ss2.png",
    "power": 5,
    "hability": 3,
    "health": 28,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGR",
    "fight_combo_damage": 23,
    "ball_combo_name": "Kamehameha final",
    "ball_combo": "PPYRR",
    "ball_combo_damage": 25,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": 28,
    "transf_cards": ""
  },
  {
    "name": "Son Gohan Super Saiyan",
    "start_card": false,
    "univers": 7,
    "picture": "son_gohan_ss.png",
    "power": 4,
    "hability": 2,
    "health": 28,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Ráfaga de bolas de energía",
    "fight_combo": "PYR",
    "fight_combo_damage": 19,
    "ball_combo_name": "Masenko",
    "ball_combo": "PYPR",
    "ball_combo_damage": 22,
    "transf_min_value": 2,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 28,
    "transf_cards": ""
  },
  {
    "name": "Son Gohan",
    "start_card": true,
    "univers": 7,
    "picture": "son_gohan.png",
    "power": 3,
    "hability": 2,
    "health": 28,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 18,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PYP",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [27,26,25]
  },
  {
    "name": "Golden Freezer",
    "start_card": false,
    "univers": 7,
    "picture": "golden_freezer.png",
    "power": 5,
    "hability": 2,
    "health": 27,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo_name": "Carga de energía",
    "fight_combo": "YYYPR",
    "fight_combo_damage": 30,
    "ball_combo_name": "Bola de la muerte",
    "ball_combo": "YYPPR",
    "ball_combo_damage": 37,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": 30,
    "transf_cards": ""
  },
  {
    "name": "Freezer",
    "start_card": true,
    "univers": 7,
    "picture": "freezer.png",
    "power": 4,
    "hability": 3,
    "health": 27,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Rayo de la muerte",
    "fight_combo": "YPP",
    "fight_combo_damage": 25,
    "ball_combo_name": "Rayo mortal",
    "ball_combo": "PRRR",
    "ball_combo_damage": 29,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,1,0,0,0,0,0,0,0,0,1,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [29]
  },
  {
    "name": "C-17",
    "start_card": true,
    "univers": 7,
    "picture": "c17.png",
    "power": 5,
    "hability": 2,
    "health": 26,
    "Y_damage": 3,
    "G_damage": 3,
    "P_damage": 3,
    "R_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo_name": "Ráfaga de bolas de energía",
    "fight_combo": "YYRR",
    "fight_combo_damage": 30,
    "ball_combo_name": "Autodestrucción",
    "ball_combo": "YPPRR",
    "ball_combo_damage": 36,
    "transf_min_value": "",
    "protection_divider": 2,
    "transf_damage": "",
    "extra_habilities": [0,0,0,1,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Dispo",
    "start_card": true,
    "univers": 11,
    "picture": "dispo.png",
    "power": 5,
    "hability": 3,
    "health": 25,
    "Y_damage": 3,
    "G_damage": 4,
    "P_damage": 3,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Justice Kick",
    "fight_combo": "YPPG",
    "fight_combo_damage": 25,
    "ball_combo_name": "Justice Crush",
    "ball_combo": "YPRRB",
    "ball_combo_damage": 30,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Caulifla Super Saiyan 2",
    "start_card": false,
    "univers": 6,
    "picture": "caulifla_ss2.png",
    "power": 5,
    "hability": 2,
    "health": 23,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPGR",
    "fight_combo_damage": 25,
    "ball_combo_name": "Oleada de energía",
    "ball_combo": "YYPRR",
    "ball_combo_damage": 29,
    "transf_min_value": 5,
    "protection_divider": 2,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 35,
    "transf_cards": ""
  },
  {
    "name": "Caulifla Super Saiyan",
    "start_card": false,
    "univers": 6,
    "picture": "caulifla_ss1.png",
    "power": 4,
    "hability": 2,
    "health": 23,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Teletransportación + encadenamiento",
    "fight_combo": "PGB",
    "fight_combo_damage": 19,
    "ball_combo_name": "Cañón devastador",
    "ball_combo": "YPRR",
    "ball_combo_damage": 21,
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": 35,
    "transf_cards": ""
  },
  {
    "name": "Caulifla",
    "start_card": true,
    "univers": 6,
    "picture": "caulifla.png",
    "power": 3,
    "hability": 2,
    "health": 23,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGG",
    "fight_combo_damage": 16,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YPR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [34,33]
  },
  {
    "name": "C-18",
    "start_card": true,
    "univers": 7,
    "picture": "c18.png",
    "power": 5,
    "hability": 2,
    "health": 24,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YPGR",
    "fight_combo_damage": 24,
    "ball_combo_name": "Ola de energía explosiva",
    "ball_combo": "YPRRR",
    "ball_combo_damage": 28,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,1,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Piccolo",
    "start_card": true,
    "univers": 7,
    "picture": "piccolo.png",
    "power": 5,
    "hability": 2,
    "health": 22,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Onda demoníaca",
    "fight_combo": "YYPR",
    "fight_combo_damage": 23,
    "ball_combo_name": "Makankosappo",
    "ball_combo": "YPGRR",
    "ball_combo_damage": 27,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,1,0,0,1,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Cabba Super Saiyan",
    "start_card": false,
    "univers": 6,
    "picture": "cabba_ss1.png",
    "power": 4,
    "hability": 2,
    "health": 21,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Carga ráfaga",
    "fight_combo": "PYR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Cañón Galick",
    "ball_combo": "YPPR",
    "ball_combo_damage": 20,
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 3,
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": 39,
    "transf_cards": ""
  },
  {
    "name": "Cabba",
    "start_card": true,
    "univers": 6,
    "picture": "cabba.png",
    "power": 3,
    "hability": 2,
    "health": 21,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [38]
  },
  {
    "name": "Koichiarator",
    "start_card": true,
    "univers": 3,
    "picture": "koichiarator.png",
    "power": 4,
    "hability": 2,
    "health": 21,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBBB",
    "fight_combo_name": "Golpe potente",
    "fight_combo": "PPRR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Vista láser",
    "ball_combo": "YYPP",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Pirina",
    "start_card": true,
    "univers": 6,
    "picture": "pirina.png",
    "power": 4,
    "hability": 2,
    "health": 20,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Brazos telescópicos",
    "fight_combo": "YPGR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Grito devastador",
    "ball_combo": "YYYR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,1,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Saonel",
    "start_card": true,
    "univers": 6,
    "picture": "saonel.png",
    "power": 4,
    "hability": 2,
    "health": 20,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Brazos telescópicos",
    "fight_combo": "PPRR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Hoja de energía",
    "ball_combo": "YYPR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,1,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Ribrianne",
    "start_card": false,
    "univers": 2,
    "picture": "ribrianne.png",
    "power": 5,
    "hability": 3,
    "health": 20,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Cañón Bonito",
    "fight_combo": "YPRR",
    "fight_combo_damage": 19,
    "ball_combo_name": "Ametralladora del amor hermoso",
    "ball_combo": "YYYRR",
    "ball_combo_damage": 23,
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 44,
    "transf_cards": ""
  },
  {
    "name": "Briand de Chateau",
    "start_card": true,
    "univers": 2,
    "picture": "brianne_dechateau.png",
    "power": 4,
    "hability": 2,
    "health": 20,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Lazo Gran Amor",
    "ball_combo": "YYPR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,1,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [43]
  },
  {
    "name": "Kakunsa",
    "start_card": false,
    "univers": 2,
    "picture": "kakunsa.png",
    "power": 5,
    "hability": 3,
    "health": 20,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 3,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Arañazos bestiales",
    "fight_combo": "PPGR",
    "fight_combo_damage": 18,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYPRR",
    "ball_combo_damage": 21,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,1,0,0,0,1,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 46,
    "transf_cards": ""
  },
  {
    "name": "Sanka Ku",
    "start_card": true,
    "univers": 2,
    "picture": "sanka_ku.png",
    "power": 4,
    "hability": 2,
    "health": 20,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YPRR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYPR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [45]
  },
  {
    "name": "Rozie",
    "start_card": false,
    "univers": 2,
    "picture": "rozie.png",
    "power": 5,
    "hability": 3,
    "health": 20,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 3,
    "R_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YPGG",
    "fight_combo_damage": 17,
    "ball_combo_name": "Puño Yacchaina",
    "ball_combo": "YPGRB",
    "ball_combo_damage": 21,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,1,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": 48,
    "transf_cards": ""
  },
  {
    "name": "Su Roas",
    "start_card": true,
    "univers": 2,
    "picture": "su_roas.png",
    "power": 4,
    "hability": 2,
    "health": 20,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Ráfaga de puños",
    "fight_combo": "PPP",
    "fight_combo_damage": 15,
    "ball_combo_name": "Estallido bola de energía",
    "ball_combo": "YYRR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [47]
  },
  {
    "name": "Frost",
    "start_card": true,
    "univers": 6,
    "picture": "frost.png",
    "power": 4,
    "hability": 3,
    "health": 20,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Rayos caóticos",
    "fight_combo": "YPR",
    "fight_combo_damage": 18,
    "ball_combo_name": "Bola caótica",
    "ball_combo": "YYPR",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "2",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Jimizu",
    "start_card": true,
    "univers": 2,
    "picture": "jimizu.png",
    "power": 4,
    "hability": 3,
    "health": 19,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Ataque instantáneo",
    "fight_combo": "RGB",
    "fight_combo_damage": 16,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYPR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,1,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Obuni",
    "start_card": true,
    "univers": 10,
    "picture": "obuni.png",
    "power": 5,
    "hability": 3,
    "health": 19,
    "Y_damage": 2,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YPPG",
    "fight_combo_damage": 16,
    "ball_combo_name": "Técnica interna Ki",
    "ball_combo": "PYRBB",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Bergamo",
    "start_card": true,
    "univers": 9,
    "picture": "bergamo.png",
    "power": 4,
    "hability": 3,
    "health": 18,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Puños y pies de energía",
    "fight_combo": "GGR",
    "fight_combo_damage": 19,
    "ball_combo_name": "Wolfgand Driller",
    "ball_combo": "YPGR",
    "ball_combo_damage": 23,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Lavender",
    "start_card": true,
    "univers": 9,
    "picture": "lavender.png",
    "power": 4,
    "hability": 2,
    "health": 17,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 3,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YPG",
    "fight_combo_damage": 18,
    "ball_combo_name": "Aliento envenenado",
    "ball_combo": "YPGR",
    "ball_combo_damage": 23,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Basil",
    "start_card": true,
    "univers": 9,
    "picture": "basil.png",
    "power": 4,
    "hability": 2,
    "health": 17,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Bláster brillante",
    "fight_combo": "GGR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Wolfgang Pressure",
    "ball_combo": "YPGR",
    "ball_combo_damage": 23,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Monna",
    "start_card": true,
    "univers": 4,
    "picture": "monna.png",
    "power": 4,
    "hability": 2,
    "health": 17,
    "Y_damage": 1,
    "G_damage": 3,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Ataque inflado",
    "fight_combo": "YPG",
    "fight_combo_damage": 17,
    "ball_combo_name": "Bola de tanque humana",
    "ball_combo": "GPRR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Maji Kayo",
    "start_card": true,
    "univers": 3,
    "picture": "maji_kayo.png",
    "power": 4,
    "hability": 2,
    "health": 16,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Metamorfosis",
    "fight_combo": "PBB",
    "fight_combo_damage": 16,
    "ball_combo_name": "Puño enorme",
    "ball_combo": "PPRR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Narirama",
    "start_card": true,
    "univers": 3,
    "picture": "narirama.png",
    "power": 4,
    "hability": 2,
    "health": 16,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Estiramiento brazo",
    "fight_combo": "PPP",
    "fight_combo_damage": 13,
    "ball_combo_name": "Peonza",
    "ball_combo": "YPG",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Krilin",
    "start_card": true,
    "univers": 7,
    "picture": "krilin.png",
    "power": 3,
    "hability": 3,
    "health": 16,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Kienza",
    "fight_combo": "YP",
    "fight_combo_damage": 17,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "YPP",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,1,"<13 BB0",0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Tenshinhan",
    "start_card": true,
    "univers": 7,
    "picture": "tenshinhan.png",
    "power": 3,
    "hability": 2,
    "health": 15,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Dodompa",
    "fight_combo": "PG",
    "fight_combo_damage": 18,
    "ball_combo_name": "Shinkikoho",
    "ball_combo": "YYP",
    "ball_combo_damage": 22,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,1,"<14 BB0",0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Damon",
    "start_card": true,
    "univers": 4,
    "picture": "damon.png",
    "power": 4,
    "hability": 2,
    "health": 15,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBB",
    "fight_combo_name": "Contraataque inalcanzable",
    "fight_combo": "PBB",
    "fight_combo_damage": 13,
    "ball_combo_name": "Ataque silencioso",
    "ball_combo": "PGR",
    "ball_combo_damage": 15,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Gamisaras",
    "start_card": true,
    "univers": 4,
    "picture": "gamisaras.png",
    "power": 4,
    "hability": 1,
    "health": 15,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Zancadilla",
    "fight_combo": "PGG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Encadenamiento",
    "ball_combo": "PPGG",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Kunshi",
    "start_card": true,
    "univers": 11,
    "picture": "kunshi.png",
    "power": 4,
    "hability": 3,
    "health": 15,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PRR",
    "fight_combo_damage": 19,
    "ball_combo_name": "Hilo de energía",
    "ball_combo": "YPPR",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Maestro Roshi Máxima Potencia",
    "start_card": false,
    "univers": 7,
    "picture": "maestro_roshi.png",
    "power": 3,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BB",
    "fight_combo_name": "Mafuba",
    "fight_combo": "PRR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPY",
    "ball_combo_damage": 16,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 64,
    "transf_cards": ""
  },
  {
    "name": "Maestro Roshi",
    "start_card": true,
    "univers": 7,
    "picture": "m_roshi.png",
    "power": 3,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Mafuba",
    "fight_combo": "PR",
    "fight_combo_damage": 14,
    "ball_combo_name": "Kamehameha",
    "ball_combo": "PPY",
    "ball_combo_damage": 15,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [63]
  },
  {
    "name": "Napapa",
    "start_card": true,
    "univers": 10,
    "picture": "napapa.png",
    "power": 4,
    "hability": 2,
    "health": 14,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 19,
    "ball_combo_name": "Técnica de las 100 manos",
    "ball_combo": "PPRR",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Magetta",
    "start_card": true,
    "univers": 6,
    "picture": "magetta.png",
    "power": 4,
    "hability": 2,
    "health": 14,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 3,
    "R_damage": 1,
    "protection_combo": "BBBB",
    "fight_combo_name": "Chorro de lava",
    "fight_combo": "PGR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Garrote de lava",
    "ball_combo": "YPRR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Kahseral",
    "start_card": true,
    "univers": 11,
    "picture": "kahseral.png",
    "power": 4,
    "hability": 2,
    "health": 14,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Justice Saber",
    "fight_combo": "PPR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Justice Bomber",
    "ball_combo": "YYRP",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Zirloin",
    "start_card": true,
    "univers": 2,
    "picture": "zirloin.png",
    "power": 3,
    "hability": 2,
    "health": 14,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Puñetazo martillo",
    "ball_combo": "YYR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Tupper",
    "start_card": true,
    "univers": 11,
    "picture": "tupper.png",
    "power": 4,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Refuerzo",
    "fight_combo": "GGR",
    "fight_combo_damage": 14,
    "ball_combo_name": "Rueda en llamas",
    "ball_combo": "YGPR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Biara",
    "start_card": true,
    "univers": 3,
    "picture": "biara.png",
    "power": 3,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Murichim",
    "start_card": true,
    "univers": 10,
    "picture": "murichim.png",
    "power": 4,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGG",
    "fight_combo_damage": 16,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YRRR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Prum",
    "start_card": true,
    "univers": 2,
    "picture": "prum.png",
    "power": 4,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Devolución Ki",
    "fight_combo": "YPG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Devolución láser",
    "ball_combo": "YYR",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,"PPR",0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Rabanra",
    "start_card": true,
    "univers": 2,
    "picture": "rabanra.png",
    "power": 4,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 17,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Paparoni",
    "start_card": true,
    "univers": 3,
    "picture": "paparoni.png",
    "power": 4,
    "hability": 2,
    "health": 13,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYRR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Zarbuto",
    "start_card": true,
    "univers": 2,
    "picture": "zarbuto.png",
    "power": 4,
    "hability": 2,
    "health": 12,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGG",
    "fight_combo_damage": 19,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYYR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Katopesla",
    "start_card": true,
    "univers": 3,
    "picture": "katopesla.png",
    "power": 4,
    "hability": 2,
    "health": 12,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBBB",
    "fight_combo_name": "Puños de energía",
    "fight_combo": "PPR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Katopesla:missión final",
    "ball_combo": "YYRR",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Botamo",
    "start_card": true,
    "univers": 6,
    "picture": "botamo.png",
    "power": 4,
    "hability": 1,
    "health": 12,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Láser",
    "fight_combo": "GGR",
    "fight_combo_damage": 14,
    "ball_combo_name": "Aplastamiento",
    "ball_combo": "YYRR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Ganos transformado",
    "start_card": false,
    "univers": 4,
    "picture": "ganos_trans.png",
    "power": 4,
    "hability": 2,
    "health": 12,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo_name": "Descarga eléctrica",
    "fight_combo": "YPR",
    "fight_combo_damage": 18,
    "ball_combo_name": "Grand Adora",
    "ball_combo": "PPRR",
    "ball_combo_damage": 21,
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": 79,
    "transf_cards": ""
  },
  {
    "name": "Ganos",
    "start_card": true,
    "univers": 4,
    "picture": "ganos.png",
    "power": 3,
    "hability": 2,
    "health": 12,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Ráfaga de bolas",
    "ball_combo": "YYR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": [78]
  },
  {
    "name": "Zoiray",
    "start_card": true,
    "univers": 11,
    "picture": "zoiray.png",
    "power": 3,
    "hability": 2,
    "health": 12,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Justice Spin",
    "fight_combo": "YPR",
    "fight_combo_damage": 14,
    "ball_combo_name": "Justice Tornado",
    "ball_combo": "PGR",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Nink",
    "start_card": true,
    "univers": 4,
    "picture": "nink.png",
    "power": 3,
    "hability": 1,
    "health": 12,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Refuerzo",
    "fight_combo": "YPG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Abrazo de oso",
    "ball_combo": "PRR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Rubalt",
    "start_card": true,
    "univers": 10,
    "picture": "rubalt.png",
    "power": 3,
    "hability": 2,
    "health": 11,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGG",
    "fight_combo_damage": 13,
    "ball_combo_name": "Puñetazo",
    "ball_combo": "PPR",
    "ball_combo_damage": 15,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Shantsa",
    "start_card": true,
    "univers": 4,
    "picture": "shantsa.png",
    "power": 3,
    "hability": 2,
    "health": 11,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 16,
    "ball_combo_name": "Campo de ilusiones",
    "ball_combo": "YYR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Kettle",
    "start_card": true,
    "univers": 11,
    "picture": "kettle.png",
    "power": 3,
    "hability": 1,
    "health": 11,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 12,
    "ball_combo_name": "Barrera de bolas",
    "ball_combo": "YYR",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Hermila",
    "start_card": true,
    "univers": 2,
    "picture": "hermila.png",
    "power": 4,
    "hability": 2,
    "health": 11,
    "Y_damage": 2,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Tir Láser",
    "ball_combo": "YYRR",
    "ball_combo_damage": 21,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Chappil",
    "start_card": true,
    "univers": 9,
    "picture": "chappil.png",
    "power": 3,
    "hability": 2,
    "health": 10,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Aliento de fuego",
    "fight_combo": "PG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Piel de hierro",
    "ball_combo": "PRR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "El Preecho",
    "start_card": true,
    "univers": 3,
    "picture": "el_preecho.png",
    "power": 3,
    "hability": 1,
    "health": 10,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 13,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYY",
    "ball_combo_damage": 15,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Vuon",
    "start_card": true,
    "univers": 11,
    "picture": "vuon.png",
    "power": 3,
    "hability": 1,
    "health": 10,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Láser",
    "fight_combo": "YRR",
    "fight_combo_damage": 17,
    "ball_combo_name": "Justice Whip",
    "ball_combo": "YYYR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Nigrissi",
    "start_card": true,
    "univers": 3,
    "picture": "nigrissi.png",
    "power": 3,
    "hability": 2,
    "health": 10,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Ataque camuflado",
    "fight_combo": "PGG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Ola de energia",
    "ball_combo": "YYPR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Majora",
    "start_card": true,
    "univers": 4,
    "picture": "majora.png",
    "power": 3,
    "hability": 2,
    "health": 10,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YRR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Darcoli",
    "start_card": true,
    "univers": 4,
    "picture": "darcoli.png",
    "power": 3,
    "hability": 2,
    "health": 10,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Ilusión",
    "fight_combo": "YPB",
    "fight_combo_damage": 13,
    "ball_combo_name": "Técnica de la sombra",
    "ball_combo": "PGB",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Bikal",
    "start_card": true,
    "univers": 2,
    "picture": "bikal.png",
    "power": 3,
    "hability": 1,
    "health": 9,
    "Y_damage": 2,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Bola de energía",
    "fight_combo": "YG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Ataque aéreo",
    "ball_combo": "YPR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Dr. Rota",
    "start_card": true,
    "univers": 6,
    "picture": "dr_rota.png",
    "power": 3,
    "hability": 1,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PPG",
    "fight_combo_damage": 13,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 15,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Hyssop",
    "start_card": true,
    "univers": 9,
    "picture": "hyssop.png",
    "power": 3,
    "hability": 1,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Lanza de hielo",
    "fight_combo": "PPY",
    "fight_combo_damage": 14,
    "ball_combo_name": "Pico de hielo",
    "ball_combo": "YYR",
    "ball_combo_damage": 17,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Dium",
    "start_card": true,
    "univers": 10,
    "picture": "dium.png",
    "power": 2,
    "hability": 1,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BB",
    "fight_combo_name": "Ataque aéreo",
    "fight_combo": "PG",
    "fight_combo_damage": 17,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YR",
    "ball_combo_damage": 19,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Sorrel",
    "start_card": true,
    "univers": 9,
    "picture": "sorrel.png",
    "power": 2,
    "hability": 1,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 12,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YR",
    "ball_combo_damage": 14,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Comfrey",
    "start_card": true,
    "univers": 9,
    "picture": "comfrey.png",
    "power": 3,
    "hability": 2,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YPY",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Cocotte",
    "start_card": true,
    "univers": 11,
    "picture": "cocotte.png",
    "power": 3,
    "hability": 2,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "GPP",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Jilcol",
    "start_card": true,
    "univers": 10,
    "picture": "jilcol.png",
    "power": 3,
    "hability": 1,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YGR",
    "fight_combo_damage": 12,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YPRR",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Shosa",
    "start_card": true,
    "univers": 4,
    "picture": "shosa.png",
    "power": 3,
    "hability": 2,
    "health": 9,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Bola de energía",
    "fight_combo": "PYG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Ráfaga de bolas",
    "ball_combo": "YPR",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Orégano",
    "start_card": true,
    "univers": 9,
    "picture": "oregano.png",
    "power": 3,
    "hability": 2,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Hilo inmovilizador",
    "fight_combo": "PR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYY",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Methiop",
    "start_card": true,
    "univers": 10,
    "picture": "methiop.png",
    "power": 3,
    "hability": 1,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "YRR",
    "fight_combo_damage": 16,
    "ball_combo_name": "Puño elástico",
    "ball_combo": "PPR",
    "ball_combo_damage": 20,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Murisarm",
    "start_card": true,
    "univers": 10,
    "picture": "murisarm.png",
    "power": 3,
    "hability": 2,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PGR",
    "fight_combo_damage": 14,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYR",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,0,0,0,0,0,0,0,1],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Roselle",
    "start_card": true,
    "univers": 9,
    "picture": "roselle.png",
    "power": 3,
    "hability": 1,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 2,
    "protection_combo": "BBB",
    "fight_combo_name": "Ataque aéreo",
    "fight_combo": "PGR",
    "fight_combo_damage": 14,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YPP",
    "ball_combo_damage": 16,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Hop",
    "start_card": true,
    "univers": 9,
    "picture": "hop.png",
    "power": 3,
    "hability": 1,
    "health": 8,
    "Y_damage": 2,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Garra rosa",
    "fight_combo": "PRR",
    "fight_combo_damage": 15,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YRR",
    "ball_combo_damage": 14,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Jirasen",
    "start_card": true,
    "univers": 10,
    "picture": "jirasen.png",
    "power": 3,
    "hability": 2,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 2,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "GPG",
    "fight_combo_damage": 13,
    "ball_combo_name": "Bola de energía",
    "ball_combo": "YYP",
    "ball_combo_damage": 15,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Caway",
    "start_card": true,
    "univers": 4,
    "picture": "caway.png",
    "power": 3,
    "hability": 2,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 2,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BBB",
    "fight_combo_name": "Martillo de energía",
    "fight_combo": "YPG",
    "fight_combo_damage": 15,
    "ball_combo_name": "Lanzaenergía",
    "ball_combo": "YPR",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  },
  {
    "name": "Lilibeu",
    "start_card": true,
    "univers": 10,
    "picture": "lilibeu.png",
    "power": 2,
    "hability": 1,
    "health": 8,
    "Y_damage": 1,
    "G_damage": 1,
    "P_damage": 1,
    "R_damage": 1,
    "protection_combo": "BB",
    "fight_combo_name": "Encadenamiento",
    "fight_combo": "PG",
    "fight_combo_damage": 14,
    "ball_combo_name": "Vuelo ardiente",
    "ball_combo": "YP",
    "ball_combo_damage": 18,
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "extra_habilities": [0,0,0,0,0,0,1,0,0,0,0,0,0,0],
    "fusion_needed": "",
    "transf_origin_card": "",
    "transf_cards": ""
  }
]