var data = [
  {
    "name": "Jiren máxima potencia",
    "start_card": false,
    "univers": 11,
    "picture": "",
    "power": 6,
    "hability": 4,
    "health": 42,
    "yellow_damage": 5,
    "green_damage": 5,
    "purple_damage": 5,
    "red_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo": "YPGRB",
    "ball_combo": "YYPPRR",
    "transf_min_value": 4,
    "protection_divider": 3,
    "transf_damage": -5,
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": ""
  },
  {
    "name": "Jiren",
    "start_card": true,
    "univers": 11,
    "picture": "jiren.png",
    "power": 5,
    "hability": 3,
    "health": 42,
    "yellow_damage": 4,
    "green_damage": 5,
    "purple_damage": 4,
    "red_damage": 5,
    "protection_combo": "BBBB",
    "fight_combo": "PPPRR",
    "ball_combo": "YYPRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "-1 dice, 0 help",
    "attack_extra": "0 help",
    "fusion_needed": ""
  },
  {
    "name": "Anilaza",
    "start_card": false,
    "univers": 3,
    "picture": "anilaza.png",
    "power": 5,
    "hability": 4,
    "health": 37,
    "yellow_damage": 4,
    "green_damage": 3,
    "purple_damage": 4,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "GPRB",
    "ball_combo": "YYPPR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": "Paparoni, Koichiarator"
  },
  {
    "name": "Son Goku Ultra Instinto",
    "start_card": false,
    "univers": 7,
    "picture": "goku_ultra_instinto.png",
    "power": 6,
    "hability": 4,
    "health": 34,
    "yellow_damage": 5,
    "green_damage": 5,
    "purple_damage": 5,
    "red_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo": "YPGRB",
    "ball_combo": "PPYRRR",
    "transf_min_value": 11,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Ultra Instinto (presagio)",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 6,
    "hability": 4,
    "health": 34,
    "yellow_damage": 4,
    "green_damage": 5,
    "purple_damage": 4,
    "red_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo": "PPGRR",
    "ball_combo": "PPYRRR",
    "transf_min_value": 10,
    "protection_divider": 3,
    "transf_damage": -4,
    "defense_extra": "counterattack",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Super Saiyan Blue + Kaioken x10",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 6,
    "hability": 3,
    "health": 34,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 4,
    "red_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo": "PPGRR",
    "ball_combo": "PPYRRR",
    "transf_min_value": 8,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Super Saiyan Blue",
    "start_card": false,
    "univers": 7,
    "picture": "goku_blue.png",
    "power": 5,
    "hability": 3,
    "health": 34,
    "yellow_damage": 3,
    "green_damage": 3,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo": "BPPG",
    "ball_combo": "PPYRR",
    "transf_min_value": 7,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "",
    "attack_extra": "1 extra dice roll",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Super SAiyan Dios",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 34,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo": "BPGR",
    "ball_combo": "PPYRR",
    "transf_min_value": 6,
    "protection_divider": 2,
    "transf_damage": -2,
    "defense_extra": "-1 dice",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Super Saiyan 3",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 34,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "PGGR",
    "ball_combo": "PPYRR",
    "transf_min_value": 5,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "no ball if PPGGR",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Super Saiyan 2",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 2,
    "health": 34,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "BPPG",
    "ball_combo": "PPYRB",
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "-1 dice roll",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku Super Saiyan",
    "start_card": false,
    "univers": 7,
    "picture": "goku_ss1.png",
    "power": 4,
    "hability": 2,
    "health": 34,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 2,
    "red_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo": "BPG",
    "ball_combo": "PPYY",
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "",
    "attack_extra": "1 extra dice",
    "fusion_needed": ""
  },
  {
    "name": "Son Goku",
    "start_card": true,
    "univers": 7,
    "picture": "goku.png",
    "power": 3,
    "hability": 2,
    "health": 34,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 1,
    "red_damage": 2,
    "protection_combo": "BBB",
    "fight_combo": "PPY",
    "ball_combo": "PPYRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "1 extra dice",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Vegeta Super Saiyan Blue Evolution",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 6,
    "hability": 4,
    "health": 33,
    "yellow_damage": 4,
    "green_damage": 5,
    "purple_damage": 4,
    "red_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo": "YPPRRR",
    "ball_combo": "YPGRRR",
    "transf_min_value": 9,
    "protection_divider": 3,
    "transf_damage": -4,
    "defense_extra": "0 help",
    "attack_extra": "0 help, only card defense",
    "fusion_needed": ""
  },
  {
    "name": "Vegeta Super Saiyan Blue",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 33,
    "yellow_damage": 3,
    "green_damage": 3,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo": "PPGR",
    "ball_combo": "YPPRR",
    "transf_min_value": 7,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "counterattack, 0 help",
    "attack_extra": "0 help",
    "fusion_needed": ""
  },
  {
    "name": "Vegeta Super Saiyan 2",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 33,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "YYPR",
    "ball_combo": "YPPRR",
    "transf_min_value": 5,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "0 help",
    "attack_extra": "0 help",
    "fusion_needed": ""
  },
  {
    "name": "Vegeta Super Saiyan",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 33,
    "yellow_damage": 2,
    "green_damage": 2,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo": "PGR",
    "ball_combo": "YYPP",
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "0 help, -1 dice roll",
    "attack_extra": "0 help",
    "fusion_needed": ""
  },
  {
    "name": "Vegeta",
    "start_card": true,
    "univers": 7,
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 33,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 2,
    "red_damage": 2,
    "protection_combo": "BBB",
    "fight_combo": "PGR",
    "ball_combo": "YPP",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "0 help",
    "attack_extra": "0 help, 1 extra dice",
    "fusion_needed": ""
  },
  {
    "name": "Toppo dios  de la destrucción",
    "start_card": false,
    "univers": 11,
    "picture": "toppo_dios.png",
    "power": 6,
    "hability": 2,
    "health": 32,
    "yellow_damage": 5,
    "green_damage": 4,
    "purple_damage": 4,
    "red_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo": "PPGGR",
    "ball_combo": "YYPGRR",
    "transf_min_value": 4,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": ""
  },
  {
    "name": "Toppo",
    "start_card": true,
    "univers": 11,
    "picture": "toppo.png",
    "power": 5,
    "hability": 4,
    "health": 32,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 5,
    "protection_combo": "BBBB",
    "fight_combo": "YYPR",
    "ball_combo": "PPRRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "counterattack",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Kefla Super Saiyan",
    "start_card": false,
    "univers": 6,
    "picture": "kefla_ss.png",
    "power": 6,
    "hability": 3,
    "health": 32,
    "yellow_damage": 3,
    "green_damage": 5,
    "purple_damage": 4,
    "red_damage": 6,
    "protection_combo": "BBBBB",
    "fight_combo": "PPYRR",
    "ball_combo": "YYRRRR",
    "transf_min_value": 3,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": "Caulifa, Kale"
  },
  {
    "name": "Kefla",
    "start_card": false,
    "univers": 6,
    "picture": "kefla.png",
    "power": 5,
    "hability": 4,
    "health": 32,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo": "PPGGR",
    "ball_combo": "YYRRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "counterattack",
    "attack_extra": "",
    "fusion_needed": "Caulifa, Kale"
  },
  {
    "name": "Kale Super Saiyan 2",
    "start_card": false,
    "univers": 6,
    "picture": "kale_ss1_dreta.png",
    "power": 6,
    "hability": 3,
    "health": 30,
    "yellow_damage": 4,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo": "PPGGR",
    "ball_combo": "YYPRRR",
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "1 extra dice",
    "attack_extra": "1 extra dice",
    "fusion_needed": ""
  },
  {
    "name": "Kale Super Saiyan 2 (fuera de control)",
    "start_card": false,
    "univers": 6,
    "picture": "kale_ss1.png",
    "power": 5,
    "hability": 3,
    "health": 30,
    "yellow_damage": 4,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 5,
    "protection_combo": "BBBB",
    "fight_combo": "PGRR",
    "ball_combo": "YYRRR",
    "transf_min_value": 5,
    "protection_divider": 3,
    "transf_damage": -4,
    "defense_extra": "no ball if PPRRR",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Kale",
    "start_card": true,
    "univers": 6,
    "picture": "kale.png",
    "power": 3,
    "hability": 4,
    "health": 30,
    "yellow_damage": 1,
    "green_damage": 1,
    "purple_damage": 1,
    "red_damage": 2,
    "protection_combo": "BBB",
    "fight_combo": "PGR",
    "ball_combo": "YYR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "-1 dice roll",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Hit",
    "start_card": true,
    "univers": 6,
    "picture": "hit.png",
    "power": 6,
    "hability": 2,
    "health": 30,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBBB",
    "fight_combo": "PGRBB",
    "ball_combo": "YPRRBB",
    "transf_min_value": "",
    "protection_divider": 3,
    "transf_damage": "",
    "defense_extra": "-2 dice roll",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Gohan Estado Definitivo",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 28,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 5,
    "protection_combo": "BBBBB",
    "fight_combo": "YPPRR",
    "ball_combo": "PPYRR",
    "transf_min_value": 5,
    "protection_divider": 3,
    "transf_damage": -3,
    "defense_extra": "",
    "attack_extra": "only card defense",
    "fusion_needed": ""
  },
  {
    "name": "Son Gohan Super Saiyan 2",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 28,
    "yellow_damage": 2,
    "green_damage": 2,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "PPGR",
    "ball_combo": "PPYRR",
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "-1 dice roll",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Gohan Super Saiyan",
    "start_card": false,
    "univers": 7,
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 28,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 2,
    "red_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo": "PYR",
    "ball_combo": "PYPR",
    "transf_min_value": 2,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "-1 dice",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Son Gohan",
    "start_card": true,
    "univers": 7,
    "picture": "son_gohan.png",
    "power": 3,
    "hability": 2,
    "health": 28,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 1,
    "red_damage": 2,
    "protection_combo": "BBB",
    "fight_combo": "PGR",
    "ball_combo": "PYP",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "1 extra dice",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Golden Freezer",
    "start_card": false,
    "univers": 7,
    "picture": "golden_freezer.png",
    "power": 5,
    "hability": 2,
    "health": 27,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo": "YYYPR",
    "ball_combo": "YYPPR",
    "transf_min_value": 4,
    "protection_divider": 2,
    "transf_damage": -3,
    "defense_extra": "counterattack, 0 help",
    "attack_extra": "0 help",
    "fusion_needed": ""
  },
  {
    "name": "Freezer",
    "start_card": true,
    "univers": 7,
    "picture": "",
    "power": 4,
    "hability": 3,
    "health": 27,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo": "YPP",
    "ball_combo": "PRRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "no ball if not invulnerable card, 0 help",
    "attack_extra": "0 help",
    "fusion_needed": ""
  },
  {
    "name": "C-17",
    "start_card": true,
    "univers": 7,
    "picture": "c17png",
    "power": 5,
    "hability": 2,
    "health": 26,
    "yellow_damage": 3,
    "green_damage": 3,
    "purple_damage": 3,
    "red_damage": 4,
    "protection_combo": "BBBB",
    "fight_combo": "YYRR",
    "ball_combo": "YPPRR",
    "transf_min_value": "",
    "protection_divider": 2,
    "transf_damage": "",
    "defense_extra": "no ball if not invulnerable card",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Dispo",
    "start_card": true,
    "univers": 11,
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 25,
    "yellow_damage": 3,
    "green_damage": 4,
    "purple_damage": 3,
    "red_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo": "YPPG",
    "ball_combo": "YPRRB",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "1 extra dice",
    "attack_extra": "1 extra dice",
    "fusion_needed": ""
  },
  {
    "name": "Caulifla Super Saiyan 2",
    "start_card": false,
    "univers": 6,
    "picture": "caulifla_ss2.png",
    "power": 5,
    "hability": 2,
    "health": 23,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "PPGR",
    "ball_combo": "YYPRR",
    "transf_min_value": 5,
    "protection_divider": 2,
    "transf_damage": -3,
    "defense_extra": "counterattack",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Caulifla Super Saiyan",
    "start_card": false,
    "univers": 6,
    "picture": "caulifla_ss1.png",
    "power": 4,
    "hability": 2,
    "health": 23,
    "yellow_damage": 1,
    "green_damage": 1,
    "purple_damage": 2,
    "red_damage": 2,
    "protection_combo": "BBBB",
    "fight_combo": "PGB",
    "ball_combo": "YPRR",
    "transf_min_value": 3,
    "protection_divider": 2,
    "transf_damage": 0,
    "defense_extra": "-1 dice roll",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Caulifla",
    "start_card": true,
    "univers": 6,
    "picture": "caulifla.png",
    "power": 3,
    "hability": 2,
    "health": 23,
    "yellow_damage": 1,
    "green_damage": 2,
    "purple_damage": 1,
    "red_damage": 2,
    "protection_combo": "BBB",
    "fight_combo": "PGG",
    "ball_combo": "YPR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "1 extra dice",
    "fusion_needed": ""
  },
  {
    "name": "C-18",
    "start_card": true,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 2,
    "health": 24,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBB",
    "fight_combo": "YPGR",
    "ball_combo": "YPRRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "no ball if not invulnerable card",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Piccolo",
    "start_card": true,
    "univers": 7,
    "picture": "",
    "power": 5,
    "hability": 2,
    "health": 22,
    "yellow_damage": 2,
    "green_damage": 3,
    "purple_damage": 2,
    "red_damage": 3,
    "protection_combo": "BBBBB",
    "fight_combo": "YYPR",
    "ball_combo": "YPGRR",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "2 extra help dice, 5 regeneration every turn",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Cabba Super Saiyan",
    "start_card": false,
    "univers": 6,
    "picture": "cabba_ss1.png",
    "power": 4,
    "hability": 2,
    "health": 21,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Cabba",
    "start_card": true,
    "univers": 6,
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 21,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Koichiarator",
    "start_card": true,
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 21,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Priina",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Saonel",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Ribrianne",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Briand de Chateau",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Kakunsa",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Sanka Ku",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Rozie",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Su Roas",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Frost",
    "start_card": "",
    "univers": "",
    "picture": "frost.png",
    "power": 4,
    "hability": 3,
    "health": 20,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Jimizu",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 3,
    "health": 19,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Obuni",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 5,
    "hability": 3,
    "health": 19,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Bergamo",
    "start_card": "",
    "univers": "",
    "picture": "bergamo.png",
    "power": 4,
    "hability": 3,
    "health": 18,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Lavender",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 17,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Basil",
    "start_card": "",
    "univers": "",
    "picture": "basil.png",
    "power": 4,
    "hability": 2,
    "health": 17,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Monna",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 17,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Maji Kayo",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 16,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Narirama",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 16,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Krilin",
    "start_card": "",
    "univers": "",
    "picture": "krilin.png",
    "power": 3,
    "hability": 3,
    "health": 16,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Tenshinhan",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 15,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Damon",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 15,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Gamisaras",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 1,
    "health": 15,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Kunshi",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 3,
    "health": 15,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Maestro Roshi Máxima Potencia",
    "start_card": "",
    "univers": "",
    "picture": "maestro_roshi.png",
    "power": 3,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Maestro Roshi",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Napapa",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 14,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Magetta",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 14,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Kahseral",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 14,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Zirloin",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 14,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Tupper",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Biara",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Murichim",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Prum",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Rabanra",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Paparoni",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 13,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Zarbuto",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 12,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Katopesla",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 12,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Botamo",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 1,
    "health": 12,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Ganos transformado",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 12,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Ganos",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 12,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Zoiray",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 12,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Nink",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 11,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Rubalt",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 11,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Shantasa",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 11,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Kettle",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 11,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Hermila",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 4,
    "hability": 2,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Chappil",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "El Preecho",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Vuon",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Nigrissi",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Majora",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Darcoli",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 10,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Bikal",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Dr. Rota",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Hyssop",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Dium",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 2,
    "hability": 1,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Sorrel",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 2,
    "hability": 1,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Comfrey",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Cocotte",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Jilcol",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Shosa",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 9,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Orégano",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Methiop",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Murisarm",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Roselle",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Hop",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 1,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Jirasen",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Caway",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 3,
    "hability": 2,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  },
  {
    "name": "Lilibeu",
    "start_card": "",
    "univers": "",
    "picture": "",
    "power": 2,
    "hability": 1,
    "health": 8,
    "yellow_damage": "",
    "green_damage": "",
    "purple_damage": "",
    "red_damage": "",
    "protection_combo": "",
    "fight_combo": "",
    "ball_combo": "",
    "transf_min_value": "",
    "protection_divider": "",
    "transf_damage": "",
    "defense_extra": "",
    "attack_extra": "",
    "fusion_needed": ""
  }
];